CC=g++
CFLAGS= -Wall -Wextra

all: compile

compile: 
	$(CC) $(CFLAGS) 1.cc 2.cc 3.cc 4.cc 5.cc main.cc help_function/help_function.cc

check:
	$(CC) $(CFLAGS) 1.cc 2.cc 3.cc 4.cc 5.cc help_function/help_function.cc